server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/<REALM>
    driver-class-name: org.postgresql.Driver
    username: nkwenti
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

keycloak:
  realm: ""
  auth-server-url: http://localhost:7000/realms/<REALM>
  client-id: Spring-Client
  client-secret: ""
  redirect-uri: http://localhost:5173/callback 